server:
  port: 8005
  servlet:
    context-path: /question

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/question?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: -1
      filters: stat,slf4j,config
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMil=3000
      useGlobalDataSourceStat: true
      filter:
        wall:
          config:
            multi-statement-allow: true
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-idle: 50
        min-idle: 10
    database: 1
  servlet:
    multipart:
      max-file-size: 3MB
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates/
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#  mvc:
#    static-path-pattern: /st/*

log:
  context: question
  path: ${question.directory}/logs

mybatis:
  type-handlers-package: com.cx.question.config
  mapper-locations: classpath*:mappers/*.xml

question:
  directory: E:\JavaProject\data\education
  txtFile: ${question.directory}\txtfile
  excelFile: ${question.directory}\excelfile